### ISSUE TITLE
[Bug] Verify fails for classes with subclasses with custom equals implementations

### ISSUE THREAD

**Issue by A-Imal** [jqno/equalsverifier#1027]
### Describe the bug

I have a case here where the EqualsVerifier returns success until 3.17.3 but fails when attempted to run with 3.17.4. Posted in Steps to reproduce the entire JUnit 5 test class where the different results for "equals_verify_parent_test_will_fail" can be observed. Could not see in the changelogs any change which would explain this behavior.

### Steps to reproduce

```java
package com.test;

import nl.jqno.equalsverifier.EqualsVerifier;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.Map;
import java.util.Objects;

class MyTestClassTest {

    @Test
    void equals_verify_parent_test_will_fail() {
        EqualsVerifier.forClass(MyFailingParentClass.class).withNonnullFields("mySubClass").verify();
    }

    @Test
    void equals_verify_parent_test_succeeds() {
        EqualsVerifier.forClass(MySuccessParentClass.class).withNonnullFields("mySubClass").verify();
    }

    @Test
    void equals_verify_inner_test_succeeds_1() {
        EqualsVerifier.forClass(MySuccessInnerClass.class).withNonnullFields("map").verify();
    }

    @Test
    void equals_verify_inner_test_succeeds_2() {
        EqualsVerifier.forClass(MyFailingInnerClass.class).withNonnullFields("map").verify();
    }

    private static class MySuccessParentClass {

        private final MySuccessInnerClass mySubClass;

        MySuccessParentClass(final MySuccessInnerClass mySubClass) {
            this.mySubClass = mySubClass;
        }

        @Override
        public final boolean equals(final Object o) {
            if (!(o instanceof MySuccessParentClass)) return false;
            final MySuccessParentClass that = (MySuccessParentClass) o;
            return Objects.equals(mySubClass, that.mySubClass);
        }

        @Override
        public final int hashCode() {
            return Objects.hashCode(mySubClass);
        }
    }

    private static class MySuccessInnerClass {

        private final Map<String, byte[]> map;

        MySuccessInnerClass(final Map<String, byte[]> map) {
            this.map = map;
        }

        @Override
        public final boolean equals(final Object o) {
            if (!(o instanceof MySuccessInnerClass)) return false;
            final MySuccessInnerClass that = (MySuccessInnerClass) o;
            return Objects.equals(map, that.map);
        }

        @Override
        public final int hashCode() {
            return Objects.hashCode(map);
        }
    }

    private static class MyFailingParentClass {

        private final MyFailingInnerClass mySubClass;

        MyFailingParentClass(final MyFailingInnerClass mySubClass) {
            this.mySubClass = mySubClass;
        }

        @Override
        public final boolean equals(final Object o) {
            if (!(o instanceof MyFailingParentClass)) return false;
            final MyFailingParentClass that = (MyFailingParentClass) o;
            return Objects.equals(mySubClass, that.mySubClass);
        }

        @Override
        public final int hashCode() {
            return Objects.hashCode(mySubClass);
        }
    }

    private static class MyFailingInnerClass {

        private final Map<String, byte[]> map;

        MyFailingInnerClass(final Map<String, byte[]> map) {
            this.map = map;
        }

        @Override
        public final boolean equals(final Object o) {
            if (this == o) {
                return true;
            }
            if (!(o instanceof MyFailingInnerClass)) {
                return false;
            }
            final MyFailingInnerClass that = (MyFailingInnerClass) o;
            if (map.size() != that.map.size()) {
                return false;
            }
            for (final Map.Entry<String, byte[]> entry : map.entrySet()) {
                if (!Arrays.equals(entry.getValue(), that.map.get(entry.getKey()))) {
                    return false;
                }
            }
            return true;
        }

        @Override
        public final int hashCode() {
            int hashCode = 0;
            for (final Map.Entry<String, byte[]> entry : map.entrySet()) {
                hashCode += entry.getKey().hashCode() ^ Arrays.hashCode(entry.getValue());
            }
            return hashCode;
        }
    }
}

```

### Error message and version number

```

EqualsVerifier found a problem in class com.test.MyTestClassTest$MyFailingParentClass.
-> Significant fields: equals does not use mySubClass, or it is stateless.

For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
(EqualsVerifier 3.17.4, JDK 21.0.5 running on classpath, on Mac OS X)
java.lang.AssertionError: EqualsVerifier found a problem in class com.test.MyTestClassTest$MyFailingParentClass.
-> Significant fields: equals does not use mySubClass, or it is stateless.

For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
(EqualsVerifier 3.17.4, JDK 21.0.5 running on classpath, on Mac OS X)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:385)
	at com.test.MyTestClassTest.equals_verify_parent_test_will_fail(MyTestClassTest.java:14)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
	at nl.jqno.equalsverifier.internal.util.Assert.assertTrue(Assert.java:53)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.assertFieldShouldHaveBeenUsed(SignificantFieldCheck.java:235)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.assertFieldShouldBeIgnored(SignificantFieldCheck.java:158)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.checkValues(SignificantFieldCheck.java:85)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.execute(SignificantFieldCheck.java:44)
	at nl.jqno.equalsverifier.internal.checkers.FieldInspector.check(FieldInspector.java:19)
	at nl.jqno.equalsverifier.internal.checkers.FieldsChecker.check(FieldsChecker.java:83)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verifyWithExamples(SingleTypeEqualsVerifierApi.java:504)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:457)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:383)
	... 4 more


nl.jqno.equalsverifier.internal.exceptions.AssertionException
	at nl.jqno.equalsverifier.internal.util.Assert.assertTrue(Assert.java:53)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.assertFieldShouldHaveBeenUsed(SignificantFieldCheck.java:235)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.assertFieldShouldBeIgnored(SignificantFieldCheck.java:158)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.checkValues(SignificantFieldCheck.java:85)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.execute(SignificantFieldCheck.java:44)
	at nl.jqno.equalsverifier.internal.checkers.FieldInspector.check(FieldInspector.java:19)
	at nl.jqno.equalsverifier.internal.checkers.FieldsChecker.check(FieldsChecker.java:83)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verifyWithExamples(SingleTypeEqualsVerifierApi.java:504)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:457)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:383)
	at com.test.MyTestClassTest.equals_verify_parent_test_will_fail(MyTestClassTest.java:14)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


```

### Code: EqualsVerifier invocation

See steps to reproduce

### Code: class under test

See steps to reproduce

**Comment by jqno** [comment]
Reproduced. I'm looking for a fix, will let you know when I have one

**Comment by jqno** [comment]
Version 3.17.5 is now syncing with Maven Central, it should solve this problem!

**Comment by A-Imal** [comment]
Thanks for the quick fix.
