### ISSUE TITLE
EqualsVerifier 2.0 does not recognize new version scheme of Java 9 (JEP 223)

### ISSUE THREAD

**Issue by don-vip** [jqno/equalsverifier#137]
# What steps will reproduce the problem?

Run any test with an Early Access of Java 9 (tested with Jigsaw b109) and EqualsVerifier 2.0
# What is the code that triggers this problem?

anything
# What error message or stack trace does EqualsVerifier give?

IllegalStateException: This JVM's version string does not seem to be valid: 9-ea
    at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:381)
    at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:370)
# What did you expect?

success (the tests are OK with Java 7 and 8).
# Which version of EqualsVerifier are you using?

2.0
# Please provide any additional information below.
- JDK9/Jigsaw EA build: https://jdk9.java.net/jigsaw/
- JEP 223: http://openjdk.java.net/jeps/223
- I already created a PR for FindBugs: https://github.com/findbugsproject/findbugs/pull/75
- example of test failing: https://josm.openstreetmap.de/jenkins/job/JOSM-Java-EarlyAccess/jdk=Jigsaw/lastCompletedBuild/testReport/org.openstreetmap.josm.command/AddCommandTest/equalsContract/

**Comment by jqno** [comment]
Thanks for reporting this. Just a few quick questions:
- Do you also get this error with older versions of EqualsVerifier? (Say, 1.7.8)
- Could you post the full stack trace, including the the "caused by" section?

**Comment by don-vip** [comment]
We were using 1.7.6 before and did not get this problem.
Unfortunately I don't get any "caused by" in the stacktrace, here's all I got:

```
junit.framework.AssertionFailedError: IllegalStateException: This JVM's version string does not seem to be valid: 9-ea
    at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:381)
    at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:370)
    at org.openstreetmap.josm.command.AddPrimitivesCommandTest.equalsContract(AddPrimitivesCommandTest.java:40)
```

is there something special to do?

**Comment by don-vip** [comment]
OK I got the stacktrace:

```
josm\core>"c:\Program Files\Java\jdk1.8.0_74\bin\java.exe" -cp %TESTCP% org.junit.runner.JUnitCore org.openstreetmap.josm.command.AddPrimitivesCommandTest
JUnit version 4.12
.
Time: 1.093

OK (1 test)


josm\core>"c:\Program Files\Java\jdk-9\bin\java.exe" -cp %TESTCP% org.junit.runner.JUnitCore org.openstreetmap.josm.command.AddPrimitivesCommandTest
JUnit version 4.12
mars 13, 2016 2:03:04 PM sun.util.PropertyResourceBundleCharset$PropertiesFileDecoder decodeLoop
INFO: Invalid or unmappable UTF-8 sequence detected. Switching encoding from UTF-8 to ISO-8859-1
.E
Time: 0.682
There was 1 failure:
1) equalsContract(org.openstreetmap.josm.command.AddPrimitivesCommandTest)
java.lang.AssertionError: IllegalStateException: This JVM's version string does not seem to be valid: 9-ea
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
        at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:381)
        at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:370)
        at org.openstreetmap.josm.command.AddPrimitivesCommandTest.equalsContract(AddPrimitivesCommandTest.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-ea/Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-ea/NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@9-ea/Method.java:531)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
        at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
Caused by: java.lang.IllegalStateException: This JVM's version string does not seem to be valid: 9-ea
        at nl.jqno.equalsverifier.internal.lib.bytebuddy.ClassFileVersion.forCurrentJavaVersion(ClassFileVersion.java:136)
        at nl.jqno.equalsverifier.internal.lib.bytebuddy.ByteBuddy.<init>(ByteBuddy.java:152)
        at nl.jqno.equalsverifier.internal.Instantiator.giveDynamicSubclass(Instantiator.java:98)
        at nl.jqno.equalsverifier.internal.Instantiator.of(Instantiator.java:58)
        at nl.jqno.equalsverifier.internal.ClassAccessor.buildObjectAccessor(ClassAccessor.java:331)
        at nl.jqno.equalsverifier.internal.ClassAccessor.getRedAccessor(ClassAccessor.java:261)
        at nl.jqno.equalsverifier.internal.ClassAccessor.getRedObject(ClassAccessor.java:249)
        at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.giveInstances(FallbackFactory.java:98)
        at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:53)
        at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:163)
        at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:146)
        at nl.jqno.equalsverifier.internal.prefabvalues.factories.AbstractReflectiveGenericFactory.determineAndCacheActualTypeTag(AbstractReflectiveGenericFactory.java:61)
        at nl.jqno.equalsverifier.internal.prefabvalues.factories.AbstractReflectiveGenericFactory.determineAndCacheActualTypeTag(AbstractReflectiveGenericFactory.java:52)
        at nl.jqno.equalsverifier.internal.prefabvalues.factories.CollectionFactory.createValues(CollectionFactory.java:36)
        at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:159)
        at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:146)
        at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveTuple(PrefabValues.java:128)
        at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveRed(PrefabValues.java:78)
        at nl.jqno.equalsverifier.AbstractDelegationChecker.checkAbstractDelegationInFields(AbstractDelegationChecker.java:74)
        at nl.jqno.equalsverifier.AbstractDelegationChecker.check(AbstractDelegationChecker.java:46)
        at nl.jqno.equalsverifier.EqualsVerifier.verifyWithoutExamples(EqualsVerifier.java:405)
        at nl.jqno.equalsverifier.EqualsVerifier.performVerification(EqualsVerifier.java:391)
        at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:364)
        ... 31 more

FAILURES!!!
Tests run: 1,  Failures: 1
```

**Comment by don-vip** [comment]
looks like the problem comes from https://github.com/raphw/byte-buddy/blob/b5c65dab7becb9c703797dff269c8b2d48e9f912/byte-buddy-dep/src/main/java/net/bytebuddy/ClassFileVersion.java

Would you like to create an issue/PR there or do you prefer I do it? :)

**Comment by don-vip** [comment]
I think I found the root cause: https://bugs.openjdk.java.net/browse/JDK-8148785

We switched at the same time from EqualsVerifier 1.7.6 to 2.0 and jdk9b106 to jdk9b108/109

**Comment by don-vip** [comment]
Issue created: https://github.com/raphw/byte-buddy/issues/106

**Comment by jqno** [comment]
Haha, I leave the house for a few hours, and you've already solved the issue for me :). Thanks!

I'll subscribe to the notifications on the issue at ByteBuddy. When he solves it, I'll make sure to update my dependencies as well.

**Comment by raphw** [comment]
I already implemented a fix but I did not see that this was merged already. However, there is one small caveat. For Java 9, I want to use the `jdk.Version` class because right now I am accessing a system property and parse it what is a privileged action. However, my current fix is going to break again once [the class is renamed](https://bugs.openjdk.java.net/browse/JDK-8144062) what requires another change and release in Byte Buddy. Expect this to work for a while but it is difficult to always fix things as they happen in the current JDK snapshot.

**Comment by jqno** [comment]
OK, thanks for the heads up!

**Comment by raphw** [comment]
I released version 1.3.4 of Byte Buddy. I also added a fallback for using the `Version` class that I remove once Java 9 is finalized so there should not be any hick-ups.

**Comment by don-vip** [comment]
wow, thanks! :+1:

**Comment by jqno** [comment]
Awesome, thanks @raphw !
I'm working on a bugfix release of 2.0 now, I'll update to the new version of ByteBuddy before I release it.

**Comment by jqno** [comment]
I've just released version 2.0.1 which contains the new version of ByteBuddy.
I downloaded the JDK9 build you referenced, and the stack trace is gone, but it seems to be replaced with a different one in some cases now. Haven't had much time to look into it yet, though.

Please let me know how it works for you!

**Comment by don-vip** [comment]
Thanks! waiting for maven central to kick in :)

**Comment by don-vip** [comment]
it works! Thanks to both of you, it's really great to have fixes so fast :+1:
