### ISSUE TITLE
Vector/Stack objects give ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mokey38** [jqno/equalsverifier#151]
# What steps will reproduce the problem?

Attempting to verify a class which contains a Vector or Stack object 
# What is the code that triggers this problem?

In the class to test:

```
public final class Foo {

 private final Stack<Integer> stack = new Stack<>();

 public Foo() {

  //Add items to stack

 }

 @Override
 public boolean equals(Object obj) {

  if (this == obj) {
   return true;
  } else if (obj == null || getClass() != obj.getClass()){
   return false;
  }

  Foo foo = (Foo) obj;
  return stack == null ? foo.stack == null : stack.equals(foo.stack);

 }

 @Override
 public int hashCode() {

  return Objects.hashCode(stack);

 }

}
```

In the unit test:

``` @Test
    public void equalsContract() {
        EqualsVerifier.forClass(Deck.class)
                .verify();
    }
```
# What error message or stack trace does EqualsVerifier give?

```
java.lang.AssertionError: ArrayIndexOutOfBoundsException: 1
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages

    at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:381)
    at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:370)
    at com.holdem.cards.TestFoo.equalsContract(TestFoo.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at java.util.Vector.elementData(Vector.java:734)
    at java.util.Vector$Itr.next(Vector.java:1142)
    at java.util.AbstractList.hashCode(AbstractList.java:540)
    at java.util.Vector.hashCode(Vector.java:992)
    at java.util.Objects.hashCode(Objects.java:98)
    at Foo.hashCode(Foo.java:47)
    at nl.jqno.equalsverifier.CachedHashCodeInitializer.getInitializedHashCode(CachedHashCodeInitializer.java:88)
    at nl.jqno.equalsverifier.ExamplesChecker.checkHashCode(ExamplesChecker.java:123)
    at nl.jqno.equalsverifier.ExamplesChecker.checkSingle(ExamplesChecker.java:85)
    at nl.jqno.equalsverifier.ExamplesChecker.check(ExamplesChecker.java:59)
    at nl.jqno.equalsverifier.EqualsVerifier.verifyWithExamples(EqualsVerifier.java:431)
    at nl.jqno.equalsverifier.EqualsVerifier.performVerification(EqualsVerifier.java:393)
    at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:364)
    ... 36 more
```
# What did you expect?

The test to pass or fail with one of the errors listed in the documentation
# Which version of EqualsVerifier are you using?

2.1.4
# Please provide any additional information below.

Adding prefab values for the Stack class as suggested in the Google group results in the expected fucntionality, namely:

```
Stack<Integer> a = new Stack<>();
a.push(1);
Stack<Integer> b = new Stack<>();
a.push(2);
EqualsVerifier.forClass(Foo.class)
        .withPrefabValues(Stack.class, a, b)
        .verify();
```

**Comment by jqno** [comment]
I've just released a fix for this in version 2.1.5.

**Comment by Stephan202** [comment]
@jqno, it [appears](https://repo1.maven.org/maven2/nl/jqno/equalsverifier/equalsverifier/2.1.5/equalsverifier-2.1.5.jar) version 2.1.5 didn't make it to Maven Central? Usually the artifact is available pretty quickly, and it's now more than 24 hours later. (Just mentioning this in case you still need to press a button somewhere.)

**Comment by jqno** [comment]
@Stephan202 Thanks for letting me know. I had indeed forgotten to press that button... It should be syncing with Maven Central right now.
