### ISSUE TITLE
Why should static fields be final?

### ISSUE THREAD

**Issue by dpolivaev** [jqno/equalsverifier#191]
# What steps will reproduce the problem?

Run following test:

~~~~
import org.junit.Test;

import nl.jqno.equalsverifier.EqualsVerifier;

public class ClassWithRecursiveStaticField {

    static ClassWithRecursiveStaticField FIELD = new ClassWithRecursiveStaticField();

    final int content = 1;

    @Test
    public void equalsContract() {
        EqualsVerifier.forClass(ClassWithRecursiveStaticField.class).usingGetClass()//
                .verify();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + content;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        ClassWithRecursiveStaticField other = (ClassWithRecursiveStaticField) obj;
        if (content != other.content) {
            return false;
        }
        return true;
    }

}
~~~~

# What error message or stack trace does EqualsVerifier give?

~~~~
java.lang.AssertionError: Recursive datastructure.
Add prefab values for one of the following types: ClassWithRecursiveStaticField.
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:392)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:378)
	at ClassWithRecursiveStaticField.equalsContract(ClassWithRecursiveStaticField.java:16)
~~~~

# What did you expect?

Test should pass because field FIELD is static and should not be considered.

Currently FallbackFactory.traverseFields(TypeTag, PrefabValues, LinkedHashSet<TypeTag>) wants to consider this field because of condition 

~~~~
boolean isStaticAndFinal = Modifier.isStatic(modifiers) && Modifier.isFinal(modifiers);
~~~~

# Which version of EqualsVerifier are you using?

Version 2.4.5

**Comment by jqno** [comment]
Thanks for the report!

EqualsVerifier doesn't consider the field as such, but it does need to instantiate static fields. People can (and unfortunately do) use them in equals methods, so they can't be left `null`.
Fields that are both static _and_ final get an exception because they're stored differently in the `.class` file, and can't always be modified even by reflection.

In your case it unfortunately means that you'll have to provide a prefab value, because your class is recursive.
