### ISSUE TITLE
though i put Warning.INHERITED_DIRECTLY_FROM_OBJECT in supress warning as suggested. it still complains about equals implementation.

### ISSUE THREAD

**Issue by udaybuie** [jqno/equalsverifier#204]
# What steps will reproduce the problem?
1) Create a class without equals implementation.
2) try to test that class with equalsVerifier(i know its foolish, but i have a generic implementation for all my test class, and few of the bean from test suit  doesn't  implement equals) 
# What is the code that triggers this problem?
import com.jpm.am.im.etf.util.AbstractMeanBeanGetClassTest;

public class RealTestextends AbstractMeanBeanGetClassTest<SimpleClass> {

    @Override
    protected SimpleClass getBeanInstance() {
        propertiesToBeIgnoredInEquals = new String[] {"studentIds"};
        return new SimpleClass ();
    }
}

Provide an example of a complete class (equals method, hashCode method, relevant fields) and a call to EqualsVerifier.

public interface SimpleInputInterface {
  public List<Long> getStudentIds();
 }

public class SimpleClass implements SimpleInputInterface {

  private List<Long> studentIds;
@Override
  public List<Long> getFundIds() {
    return null;
  }
}
public abstract class AbstractMeanBeanGetClassTest<T> {

protected String[] propertiesToBeIgnoredInEquals = {};
@Test
    public void equalsAndHashCodeContract() {
        EqualsVerifier.forClass(getBeanInstance().getClass()).usingGetClass().
                withIgnoredFields(propertiesToBeIgnoredInEquals).
                withPrefabValues(Date.class, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()-1000)).
                withPrefabValues(Timestamp.class, new Timestamp(System.currentTimeMillis()), new Timestamp(System.currentTimeMillis()-1000)).
                suppress(Warning.STRICT_INHERITANCE, Warning.NONFINAL_FIELDS, Warning.INHERITED_DIRECTLY_FROM_OBJECT).verify();
    }

 protected abstract T getBeanInstance();
}

import com.jpm.am.im.etf.util.AbstractMeanBeanGetClassTest;

public class RealTestextends AbstractMeanBeanGetClassTest<SimpleClass> {

    @Override
    protected SimpleClass getBeanInstance() {
        propertiesToBeIgnoredInEquals = new String[] {"studentIds"};
        return new SimpleClass ();
    }
}
Remember, you have the problem right in front of you. I have to try and reproduce it in my spare time. Please help me, so that I can help you!

# What error message or stack trace does EqualsVerifier give?
java.lang.AssertionError: Significant fields: equals does not use studentIds.
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages

	at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:384)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:370)
	at com.jpm.am.im.etf.util.AbstractMeanBeanGetClassTest.equalsAndHashCodeContract(AbstractMeanBeanGetClassTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
# What did you expect?
as i have kept Warning.INHERITED_DIRECTLY_FROM_OBJECT, it shouldn't complain about equals.
# Which version of EqualsVerifier are you using?
2.3.3
# Please provide any additional information below.

**Comment by jqno** [comment]
Hi,

Unfortunately your code doesn't help me understand your problem, since it doesn't compile, so I have to guess about what your problem is.

`Warning.INHERITED_DIRECTLY_FROM_OBJECT` only has an effect when your class doesn't define an `equals` method. The stack trace that you post is about significant fields, so you either have to ignore the field that it complains about (`studentIds`) or use `Warning.ALL_FIELDS_SHOULD_BE_USED`.

**Comment by jqno** [comment]
I'm closing issues that haven't seen activity in a while -- if this is still a problem for you, please re-open this issue and give me the information that I need to help you.
