### ISSUE TITLE
Having problems with JavaFX bean

### ISSUE THREAD

**Issue by MarceloRuiz** [jqno/equalsverifier#205]
# What steps will reproduce the problem?
Create a JavaFx bean class with a property.

# What is the code that triggers this problem?
Calling EqualsVerifier on the JavaFX Bean class.

Provide an example of a complete class (equals method, hashCode method, relevant fields) and a call to EqualsVerifier.

Sample class:

    final class Tester {
	
	private final StringProperty nameProperty = new SimpleStringProperty();

	String getName() {
	    return nameProperty.get();
	}

	void setName(final String name) {
	    nameProperty.set(name);
	}

	StringProperty nameProperty() {
	    return nameProperty;
	}
	
	@Override
	public int hashCode() {
	    return Objects.hash(Tester.class.getSimpleName());  // basic, but should work
	}

	@Override
	public boolean equals(final Object obj) {
	    if (obj == null) {
		return false;
	    }
	    if (!(obj instanceof Tester)) {
		return false;
	    }
	    final Tester other = (Tester) obj;
	    return Objects.equals(this.getName(), other.getName());
	}
	
	@Override
	public String toString() {
	    return "Tester [getName()=" + getName() + "]";
	}
    }

Equals Verifier call:

    @Test(timeout = 1000)
    public void verfifyEquals() {
	EqualsVerifier.forClass(Tester.class)
	        .verify();
	
    }

Fails with:

```
java.lang.AssertionError: Non-nullity: equals throws NullPointerException on field nameProperty.
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:375)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:361)
	at com.jfx.domain.entities.tests.SupplierTest.verfifyEquals(SupplierTest.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException
	at com.jfx.domain.entities.tests.SupplierTest$Tester.getName(SupplierTest.java:112)
	at com.jfx.domain.entities.tests.SupplierTest$Tester.equals(SupplierTest.java:138)
	at nl.jqno.equalsverifier.internal.checkers.NullChecker$NullPointerExceptionFieldCheck$1.run(NullChecker.java:67)
	at nl.jqno.equalsverifier.internal.checkers.NullChecker$NullPointerExceptionFieldCheck.handle(NullChecker.java:89)
	at nl.jqno.equalsverifier.internal.checkers.NullChecker$NullPointerExceptionFieldCheck.performTests(NullChecker.java:63)
	at nl.jqno.equalsverifier.internal.checkers.NullChecker$NullPointerExceptionFieldCheck.execute(NullChecker.java:57)
	at nl.jqno.equalsverifier.internal.util.FieldInspector.check(FieldInspector.java:26)
	at nl.jqno.equalsverifier.internal.checkers.NullChecker.check(NullChecker.java:32)
	at nl.jqno.equalsverifier.EqualsVerifier.verifyWithoutExamples(EqualsVerifier.java:399)
	at nl.jqno.equalsverifier.EqualsVerifier.performVerification(EqualsVerifier.java:385)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:358)
	... 13 more
```

# What did you expect?
Not to have a NullPointerException on a field that cannot be null... and I think the test should succeed, but I am not an expert! 

# Which version of EqualsVerifier are you using?
2.5.2

# Please provide any additional information below.

**Comment by jqno** [comment]
Unfortunately, EqualsVerifier is not as smart as a human. It can see that there's a field called `nameProperty` of type `StringProperty` which is final, but it can't see that it's initialized when the class is constructed. Therefore, it will do all the null checks it would do on a normal field.

I realise it's not ideal, but there's no real way to avoid this. So the only thing you can do is call `.suppress(Warning.NULL_FIELDS)` or put a `@NonNull` annotation on the field.
