### ISSUE TITLE
Generating VMID is slow due to usage of SecureRandom

### ISSUE THREAD

**Issue by turbanoff** [jqno/equalsverifier#235]
Simple unit test which checks equality of 5 classes took 8 seconds to run.
I checked what library is actually doing. At least 5 seconds of it - JVM spends here:

    "main@1" prio=5 tid=0x1 nid=NA waiting
      java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at sun.security.provider.SeedGenerator$ThreadedSeedGenerator.getSeedByte(SeedGenerator.java:404)
	  at sun.security.provider.SeedGenerator$ThreadedSeedGenerator.getSeedBytes(SeedGenerator.java:393)
	  at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:144)
	  at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:203)
	  at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:221)
	  - locked <0x5e3> (a sun.security.provider.SecureRandom)
	  at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
	  at java.rmi.dgc.VMID.<clinit>(VMID.java:60)
	  at nl.jqno.equalsverifier.internal.prefabvalues.JavaApiPrefabValues.addAncientJavaApiClasses(JavaApiPrefabValues.java:322)
	  at nl.jqno.equalsverifier.internal.prefabvalues.JavaApiPrefabValues.addJavaClasses(JavaApiPrefabValues.java:88)
	  at nl.jqno.equalsverifier.internal.prefabvalues.JavaApiPrefabValues.build(JavaApiPrefabValues.java:72)
	  at nl.jqno.equalsverifier.internal.util.Configuration.build(Configuration.java:64)
	  at nl.jqno.equalsverifier.EqualsVerifierApi.buildConfig(EqualsVerifierApi.java:354)
	  at nl.jqno.equalsverifier.EqualsVerifierApi.performVerification(EqualsVerifierApi.java:346)
	  at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:302)
	  at com.devexperts.dxcore.api.EqualityUnitTest.testAccountActionCriteria(EqualityUnitTest.java:24)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	  at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Is it possible to adjust code to generate VMID lazily?

PS. Also I noticed that some of NoSuchFieldError throwed during test-run.
Looks like verifier tries to _copy_ static field from one object to another. Is it expected?
![image](https://user-images.githubusercontent.com/741251/54347626-69f15200-4658-11e9-87af-8175df5e77f2.png)

**Comment by Stephan202** [comment]
Drive-by comment, semi-related: consider running tests with `-Djava.security.egd=file:/dev/./urandom`. This setting is Windows/Mac/Linux and [JDK-6202721](https://bugs.openjdk.java.net/browse/JDK-6202721) compatible and will cause `SecureRandom` to be less secure but much faster; a fine trade-off when running unit tests.

(Caveat: didn't test whether there is a speedup on Windows; depends on how the non-existence of this file is handled. On Linux the difference is very noticeable.)

**Comment by jqno** [comment]
Hi!

I didn't realise `VMID` took so much time! Thanks for letting me know. I can definitely generate that lazily. I'll let you know when I have a new release. In the mean time, @Stephan202 's workaround might be of help. (Haven't tested that myself.)

And yes, copying static fields is expected (maybe a little overkill, but it makes the code easier for me). Can you tell me more about these NoSuchFieldErrors? Are they a problem for you, and if yes, in what way?


Jan

**Comment by turbanoff** [comment]
Not real problem with NoSuchFieldError. Just trying to speed up our tests.

**Comment by jqno** [comment]
I've released version 3.1.7, which loads `VMID` lazily. Please let me know if this solves your problem.

**Comment by turbanoff** [comment]
Thank you for fast response. Can confirm that it solves problem.
