### ISSUE TITLE
Add support for JDK13

### ISSUE THREAD

**Issue by ekoutanov** [jqno/equalsverifier#240]
# What steps will reproduce the problem?
Run equalsverifier on jdk13
(using **openjdk version "13-null" 2019-09-17** on macOS)

# What error message or stack trace does EqualsVerifier give?
```
java.lang.AssertionError: EqualsVerifier found a problem in class Foo.
-> Unsupported class file major version 57

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:308)
	at com.liquibet.katana.model.bet.ToteBetPlacementTest.testEqualsHashCode(ToteBetPlacementTest.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 57
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:184)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:166)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:152)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:82)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1174)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1160)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$AbstractBase.describe(TypePool.java:408)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$AbstractBase$Hierarchical.describe(TypePool.java:471)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default$LazyTypeDescription$TokenizedGenericType.toErasure(TypePool.java:6503)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default$LazyTypeDescription$GenericTypeToken$Resolution$Raw$RawAnnotatedType.of(TypePool.java:3905)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default$LazyTypeDescription$GenericTypeToken$Resolution$Raw.resolveReturnType(TypePool.java:3795)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyMethodDescription.getReturnType(TypePool.java:7060)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.description.method.MethodDescription$AbstractBase.equals(MethodDescription.java:875)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.matcher.EqualityMatcher.matches(EqualityMatcher.java:46)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.matcher.DefinedShapeMatcher.matches(DefinedShapeMatcher.java:49)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.matcher.DefinedShapeMatcher.matches(DefinedShapeMatcher.java:27)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
	at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyAnnotationDescription.getValue(TypePool.java:6169)
	at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.lambda$buildAnnotationProperties$18(AnnotationCacheBuilder.java:135)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.buildAnnotationProperties(AnnotationCacheBuilder.java:134)
	at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.cacheSupportedAnnotations(AnnotationCacheBuilder.java:123)
	at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.lambda$visitFields$6(AnnotationCacheBuilder.java:96)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.lambda$visitFields$8(AnnotationCacheBuilder.java:96)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.visitFields(AnnotationCacheBuilder.java:91)
	at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.visitType(AnnotationCacheBuilder.java:47)
	at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.build(AnnotationCacheBuilder.java:35)
	at nl.jqno.equalsverifier.internal.util.Configuration.buildAnnotationCache(Configuration.java:79)
	at nl.jqno.equalsverifier.internal.util.Configuration.build(Configuration.java:67)
	at nl.jqno.equalsverifier.EqualsVerifierApi.buildConfig(EqualsVerifierApi.java:354)
	at nl.jqno.equalsverifier.EqualsVerifierApi.performVerification(EqualsVerifierApi.java:346)
	at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:302)
	... 46 more
```

# Which version of EqualsVerifier are you using?
3.1.8

**Comment by jqno** [comment]
Thanks for reporting that. I have a fix for this, I'll try to release it some time this week.

**Comment by jqno** [comment]
Version 3.1.9 is released!

**Comment by ekoutanov** [comment]
Verified!

**Comment by jqno** [comment]
Thanks!
