### ISSUE TITLE
Add suppress option to skip hashCode check

### ISSUE THREAD

**Issue by CrushaKRool** [jqno/equalsverifier#246]
# What steps will reproduce the problem?
1. Have a class that only implements `equals()` and not `hashCode()`.
2. Execute the EqualsVerifier test.

# What is the code that triggers this problem?

```
public class MyObject
{
  private long id;

  public long getId()
  {
    return id;
  }

  public void setId( long id )
  {
    this.id = id;
  }

  @Override
  public boolean equals( Object obj )
  {
    if ( this == obj )
      return true;
    if ( obj == null )
      return false;
    if ( getClass() != obj.getClass() )
      return false;
    MyObject other = (MyObject) obj;
    if ( id != other.id )
      return false;
    return true;
  }

}
```

```
public class MyObjectTest
{
  @Test
  public void testEqualsObject()
  {
    EqualsVerifier.forClass( MyObject.class )
      .usingGetClass()
      .suppress( Warning.STRICT_INHERITANCE )
      .suppress( Warning.NONFINAL_FIELDS )
      .suppress( Warning.STRICT_HASHCODE )
      .verify();
  }
}
```

# What error message or stack trace does EqualsVerifier give?
```
java.lang.AssertionError: EqualsVerifier found a problem in class MyObject.
-> hashCode: hashCodes should be equal:
  test.MyObject@458c1321 (1166807841)
and
  test.MyObject@11438d26 (289639718)

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:305)
	at test.MyObjectTest.testEqualsObject(MyObjectTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
	at nl.jqno.equalsverifier.internal.util.Assert.assertEquals(Assert.java:26)
	at nl.jqno.equalsverifier.internal.checkers.ExamplesChecker.checkHashCode(ExamplesChecker.java:128)
	at nl.jqno.equalsverifier.internal.checkers.ExamplesChecker.checkSingle(ExamplesChecker.java:72)
	at nl.jqno.equalsverifier.internal.checkers.ExamplesChecker.check(ExamplesChecker.java:46)
	at nl.jqno.equalsverifier.EqualsVerifierApi.verifyWithExamples(EqualsVerifierApi.java:380)
	at nl.jqno.equalsverifier.EqualsVerifierApi.performVerification(EqualsVerifierApi.java:350)
	at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:302)
	... 24 more
```

# What did you expect?

Something akin to `suppress( Warning.STRICT_HASHCODE )` that allows to skip the `hashCode()` check.

# Which version of EqualsVerifier are you using?

3.1.5

# Please provide any additional information below.

I know this goes against all good programming rules and that the equals-hashCode contract is there for a reason. But in some cases we are only interested in the `equals()` method as a means to compare two instances of entirely mutable classes, and instances of those classes will never be used as keys in hash maps. And even if they were, calculating the `hashCode()` based on mutable state would do more harm than good in that case, so it's actually preferable to use the immutable memory address for that.

We would still like to use this library to test our `equals()` methods thoroughly and don't want tests to fail because we decided not to care about `hashCode()`.

**Comment by jqno** [comment]
OK, I see why you would want this. I'm willing to add it, but I'm not sure yet how I want to do it. If I just add a new `Warning.IGNORE_HASHCODE` or something similar, I think people will start using that all the time instead of `Warning.STRICT_HASHCODE`, even if `Warning.STRICT_HASHCODE` would be better and/or more appropriate for their situation. So maybe it should be mandatory to suppress both at the same time if you want the behaviour you describe, but that also feels strange.

**Comment by CrushaKRool** [comment]
In the end you could also argue that even using an autogenerated `hashCode()` implementation would still be better than breaking the contract with `equals()`.
If it never gets used, there would be no harm anyway regardless of the implementation. But if you actually do end up utilizing it, then having one that follows the contract would still be better than one that breaks it. If you change a mutable property of the object while it's in a HashMap, you would end up breaking it regardless of the implementation.
The more I think about it, the less invested I actually am. This would solely be a workaround because people are afraid to touch legacy code and change behavior, even though the behavior is wrong.

And in the end there actually is a workaround to use the framework even without implementing `hashCode()`: Instead of calling `validate()` in the end, call `report()`. Then fail the test if the message from the report contains anything but the the message about the incorrect `hashCode()` implementation. Not the cleanest way, but actually workable.

So yeah. Maybe consider this request as retracted. I can't think think of a use case where implementing `equals()` without `hashCode()` is actually less harmful than implementing both. The only risk might come from null pointers in the `hashCode()` implementation, but that can be worked around by autogeneration via IDE (and by actually using this framework).

**Comment by jqno** [comment]
OK, in that case I'll close the issue. If your change your mind in the future, feel free to re-open :).

And indeed, I think using `report()` is a good way to achieve what you wanted initially.
