### ISSUE TITLE
Updating from 1.7.2 to 3.1.10 breaks

### ISSUE THREAD

**Issue by SElab2019** [jqno/equalsverifier#258]
When I try to upgrade EqualsVerifier from 1.7.2 to version 3.1.10. The following code breaks:
```
public class Testequalsverifier {
	
	@Test
	public void demo() {
        EqualsVerifier.forClass(AppTest.class).usingGetClass().verify();
	}

}
```
The AppTest.class can be any class. The code should pass, but it throws an error:
```
java.lang.AssertionError: EqualsVerifier found a problem in class AppTest.
-> Equals is inherited directly from Object.
Suppress Warning.INHERITED_DIRECTLY_FROM_OBJECT to skip this check.

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:305)
	at UTD.SeLab.BBI.BugDetection.Testequalsverifier.demo(Testequalsverifier.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
	at nl.jqno.equalsverifier.internal.util.Assert.fail(Assert.java:65)
	at nl.jqno.equalsverifier.internal.checkers.SignatureChecker.checkEqualsIsDefined(SignatureChecker.java:43)
	at nl.jqno.equalsverifier.internal.checkers.SignatureChecker.check(SignatureChecker.java:35)
	at nl.jqno.equalsverifier.EqualsVerifierApi.verifyWithoutExamples(EqualsVerifierApi.java:368)
	at nl.jqno.equalsverifier.EqualsVerifierApi.performVerification(EqualsVerifierApi.java:349)
	at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:302)
	... 24 more
```

**Comment by jqno** [comment]
In [version 2.0](https://github.com/jqno/equalsverifier/blob/master/CHANGELOG.md#20---2016-03-06), a check was introduced to warn when `equals` and `hashCode` aren't overridden in a class. To fix this issue, you can do two things:
- not call EqualsVerifier on this class anymore (since there's no `equals` method to verify), or
- add a `.suppress(Warning.INHERITED_DIRECTLY_FROM_OBJECT)` line to the EqualsVerifier call, as the error message suggests.

**Comment by jqno** [comment]
For such a "big" upgrade, it might help to check out the migration guides as well:
* https://jqno.nl/equalsverifier/migration1to2
* https://jqno.nl/equalsverifier/migration2to3
