### ISSUE TITLE
False-positive "Significant fields: equals relies on interval, but hashCode does not." due to unsuitable generated test values

### ISSUE THREAD

**Issue by rschuetz** [jqno/equalsverifier#259]
# What steps will reproduce the problem?

See code below.

# What is the code that triggers this problem?

```
import java.util.Objects;

import org.junit.Test;
import org.threeten.extra.Interval;

import nl.jqno.equalsverifier.EqualsVerifier;

public class EqualsVerifierIssue
{
    public static final class Testee
    {
        private final Interval interval;

        public Testee(final Interval interval)
        {
            this.interval = interval;
        }

        @Override
        public boolean equals(final Object o)
        {
            if (o == null || getClass() != o.getClass())
            {
                return false;
            }

            if (o == this)
            {
                return true;
            }

            final Testee other = (Testee) o;

            return Objects.equals(interval, other.interval);
        }

        @Override
        public int hashCode()
        {
            return Objects.hash(interval);
        }

        @Override
        public String toString()
        {
            return String.format("Testee [interval=%s]", interval);
        }
    }

    @Test
    public void testEqualsAndHashcode()
    {
        EqualsVerifier.forClass(Testee.class).verify();
    }
}
```

# What error message or stack trace does EqualsVerifier give?

```
java.lang.AssertionError: EqualsVerifier found a problem in class Testee.
-> Significant fields: equals relies on interval, but hashCode does not.
  Testee [interval=-1000000000-01-01T00:00:00Z/-1000000000-01-01T00:00:00Z] has hashCode 31
  Testee [interval=+1000000000-12-31T23:59:59.999999999Z/+1000000000-12-31T23:59:59.999999999Z] has hashCode 31

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:305)
	at EqualsVerifierIssue.testEqualsAndHashcode(EqualsVerifierIssue.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
	at nl.jqno.equalsverifier.internal.util.Assert.assertFalse(Assert.java:40)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.assertEqualsAndHashCodeRelyOnSameFields(SignificantFieldCheck.java:79)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.execute(SignificantFieldCheck.java:62)
	at nl.jqno.equalsverifier.internal.checkers.FieldInspector.check(FieldInspector.java:27)
	at nl.jqno.equalsverifier.internal.checkers.FieldsChecker.check(FieldsChecker.java:65)
	at nl.jqno.equalsverifier.EqualsVerifierApi.verifyWithExamples(EqualsVerifierApi.java:380)
	at nl.jqno.equalsverifier.EqualsVerifierApi.performVerification(EqualsVerifierApi.java:350)
	at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:302)
	... 24 more
```

# What did you expect?

A successful test.

# Which version of EqualsVerifier are you using?

3.1.10

# Please provide any additional information below.

The Interval class (from https://mvnrepository.com/artifact/org.threeten/threeten-extra/1.5.0) implements hashCode like this:
```
@Override
    public int hashCode() {
        return start.hashCode() ^ end.hashCode();
    }
```
EqualsVerifier unfortunately selects the same values for start and end when creating the test intervals, resulting into different intervals with the same hash code. Maybe it would be an option to check the generated intervals for different hash codes first before using them to test the testee.

Using prefab values solves the issue, but is this really the right way to have to supply test intervals manually in this case?

**Comment by jqno** [comment]
Thanks for the elaborate report, it makes it easy to reproduce and analyse things :).

I'm afraid that using a prefab value is indeed the best, solution here. The alternative is for me is to add built-in support for Interval (and possibly other classes in Threeten), which I'm hesitant to do, because it adds another dependency to the project.

Checking the hashcode as you suggest is possible, but because of the way EqualsVerifier is built, the best thing it can do in that case is throw a slightly more specific error message than the one you already got. I can't make it generate different values in that case without rewriting most of EqualsVerifier.

**Comment by rschuetz** [comment]
Thanks for checking. Maybe a better error message and some more information on https://jqno.nl/equalsverifier/errormessages/significant-fields-equals-relies-on-foo-but-hashcode-does-not/ would help already.

**Comment by jqno** [comment]
OK, I'll see what I can do. Might take a while due to the holidays, but I'll let you know.

**Comment by jqno** [comment]
I've updated the website.
