### ISSUE TITLE
Error message "Significant fields: equals does not use <myfield>, or it is stateless." not explained

### ISSUE THREAD

**Issue by kwin** [jqno/equalsverifier#309]
I get the following error message with version 3.3
```
java.lang.AssertionError: EqualsVerifier found a problem in class ....
-> Significant fields: equals does not use <myfield>, or it is stateless.

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:269)
	...
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
	at nl.jqno.equalsverifier.internal.util.Assert.assertTrue(Assert.java:52)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.assertFieldShouldHaveBeenUsed(SignificantFieldCheck.java:172)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.assertFieldShouldBeIgnored(SignificantFieldCheck.java:121)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.execute(SignificantFieldCheck.java:67)
	at nl.jqno.equalsverifier.internal.checkers.FieldInspector.check(FieldInspector.java:26)
	at nl.jqno.equalsverifier.internal.checkers.FieldsChecker.check(FieldsChecker.java:71)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verifyWithExamples(SingleTypeEqualsVerifierApi.java:363)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:321)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:267)
	... 24 more
```

That error message is not explained though at <https://jqno.nl/equalsverifier/errormessages/>.

**Comment by jqno** [comment]
Added an explanation: https://jqno.nl/equalsverifier/errormessages/significant-fields-equals-does-not-use-foo-or-it-is-stateless/
