### ISSUE TITLE
Using getter that requires non-null value in equals/hashCode throws NPE

### ISSUE THREAD

**Issue by hisener** [jqno/equalsverifier#319]
# What steps will reproduce the problem?

`EqualsVerifier.forClass(TypeWithFinalField.class).verify();` for the class below throws NPE.

# What is the code that triggers this problem?

```
static final class TypeWithFinalField {
    private final List<String> list = new ArrayList<>();

    public List<String> getList() {
        return Objects.requireNonNull(list); // in reality, it is ImmutableList.copyOf(list);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TypeWithFinalField that = (TypeWithFinalField) o;
        return Objects.equals(getList(), that.getList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getList());
    }
}
```

You may ask why do you even use the getter in `equals` and `hashCode`. The reason is that this field is in the abstract class and it is private. Something like:

```
static abstract class AbstractType {
    private final List<String> list = new ArrayList<>(); // in reality, it is ImmutableList.copyOf(list);

    public List<String> getList() {
        return Objects.requireNonNull(list);
    }
}

static final class ConcreteType extends AbstractType {
    @Override
    public int hashCode() {
        return Objects.hash(getList());
    }

    @Override
    public boolean equals(Object obj) {
        // ...
        return Objects.equals(getList(), that.getList());
    }
}
```

# What error message or stack trace does EqualsVerifier give?

```
java.lang.AssertionError: EqualsVerifier found a problem in class nl.jqno.equalsverifier.integration.basic_contract.FinalFieldTest$TypeWithFinalField.
-> Non-nullity: equals throws NullPointerException on field list.

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages

	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:269)
	at nl.jqno.equalsverifier.integration.basic_contract.FinalFieldTest.typeWithFinalFieldUsingGetterInEqualsAndHashCode(FinalFieldTest.java:13)
Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
	at nl.jqno.equalsverifier.internal.util.Assert.fail(Assert.java:75)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.npeThrown(NullPointerExceptionFieldCheck.java:75)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.handle(NullPointerExceptionFieldCheck.java:60)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.performTests(NullPointerExceptionFieldCheck.java:48)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.execute(NullPointerExceptionFieldCheck.java:42)
	at nl.jqno.equalsverifier.internal.checkers.FieldInspector.check(FieldInspector.java:26)
	at nl.jqno.equalsverifier.internal.checkers.NullChecker.check(NullChecker.java:23)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verifyWithoutExamples(SingleTypeEqualsVerifierApi.java:352)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:320)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:267)
	... 25 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at nl.jqno.equalsverifier.integration.basic_contract.FinalFieldTest$TypeWithFinalField.getList(FinalFieldTest.java:20)
	at nl.jqno.equalsverifier.integration.basic_contract.FinalFieldTest$TypeWithFinalField.equals(FinalFieldTest.java:28)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.lambda$performTests$0(NullPointerExceptionFieldCheck.java:48)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.handle(NullPointerExceptionFieldCheck.java:58)
	... 32 more
```

# What did you expect?

It throws NPE because it uses reflection to set the field to `null`. I am not sure this is the correct behavior since the field is `final`.

I tried to use `or` instead of `and` in the following line but it didn't solve the NPE. 🤔 

https://github.com/jqno/equalsverifier/blob/9fd717dfa53c1f63284129fbb52d3494722b18ee/src/main/java/nl/jqno/equalsverifier/internal/reflection/FieldAccessor.java#L210

# Which version of EqualsVerifier are you using?

3.4.1

# Please provide any additional information below.

**Comment by jqno** [comment]
The way EqualsVerifier uses to instantiates objects, bypasses the constructor and any instance initializations such as this one. This is done by design, and there's a bunch of reasons for it. For instance, a constructor doesn't always allow every field to be controlled specifically, and reflection does. Also, constructors and initializers might throw exceptions, thereby hiding potential issues. The disadvantage is that properly enforced invariants, such as yours, are not respected.

If you don't want to do null checks in your equals method (and it makes a lot of sense not to in your case), you can use use a `@NonNull` annotation of some kind, or `.suppress(Warning.NULL_FIELDS)`.

The specific line of code in EqualsVerifier that you refer to, pertains specifically to static final fields of primitive or `String` type, which are in-lined in the bytecode and therefore can't be modified using reflection even if you try.
