### ISSUE TITLE
java.lang.AbstractMethodError for abstract equals(java.lang.Object) reachable via field in super-type

### ISSUE THREAD

**Issue by monochromata** [jqno/equalsverifier#486]
**Describe the bug**
EqualsVerifier creates dynamic subclasses of types of nested fields. I'm using a type that re-declares `Object.equals(Object)` as abstract method. The dynamically-generated subclasses do not implement these methods so invocations of `equals(Object)` fail.

![Bildschirmfoto vom 2021-08-26 20-39-57](https://user-images.githubusercontent.com/4191126/131019351-0c358793-65ed-470c-9e6f-a20099200d7b.png)
![Bildschirmfoto vom 2021-08-26 20-39-45](https://user-images.githubusercontent.com/4191126/131019360-b2e556d1-7df4-4ef1-aae4-dce0112ff342.png)

**To Reproduce**
See code below.

**Code that triggers the behavior**

***Example 1(can be worked around :heart:)***

Invocation of EqualsVerifier:

```java
        EqualsVerifier.forClass(Pact.class)
            .usingGetClass()
            // will do the trick: .withPrefabValues(JsonNode.class, NullNode.instance, new TextNode("foo"))
            .withIgnoredFields("pactId")
            .suppress(STRICT_INHERITANCE)
            .verify();
```

Relevant code:

```java
// ...
public class Pact extends PactLike<Interaction> {
// ...
```

```java
// ...
public abstract class PactLike<I extends Interaction> implements Identified {
    // ...
    public final List<I> interactions;
```

```java
// ...
public class Interaction extends Invocation {
    public final FieldsProviderState providerState;
    // ...
    // equals(...) and hashCode() cover providerState
```

```java
// ...
public class FieldsProviderState implements State {
    public final Map<String,Object> fieldValues;
    // The introduction of the following field introduced the problem - verification succeeds without the field
    public final transient JsonNode fieldValuesJson;
    // equals(...) and hashCode() do NOT cover fieldValuesJson
```

```java
package com.fasterxml.jackson.databind;
// ...
public abstract class JsonNode
    extends JsonSerializable.Base // i.e. implements JsonSerializable
    implements TreeNode, Iterable<JsonNode>
{
    // ...
   @Override
    public abstract boolean equals(Object o);
    // Note that hashCode() is not overwritten
```

Error message:
```
java.lang.AssertionError: EqualsVerifier found a problem in class de.monochromata.contract.pact.Pact.
-> Missing implementation of resolved method 'abstract boolean equals(java.lang.Object)' of abstract class com.fasterxml.jackson.databind.JsonNode.

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:294)
	at de.monochromata.contract.pact.PactStepdefs.equalsVerifier(PactStepdefs.java:133)
	at ✽.de.monochromata.contract.pact.Pact has prefabricated values and correct hashcode and equals methods(classpath:de/monochromata/contract/pact/Pact.feature:60)
Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract boolean equals(java.lang.Object)' of abstract class com.fasterxml.jackson.databind.JsonNode.
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveOther(PrefabValues.java:109)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$changeField$2(FieldModifier.java:97)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$change$3(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.util.Rethrow.lambda$rethrow$0(Rethrow.java:47)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:30)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:45)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:55)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:100)
	at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:52)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:174)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:163)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.giveInstances(FallbackFactory.java:95)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:40)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:155)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:138)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.traverseFields(FallbackFactory.java:88)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:39)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:155)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:138)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.AbstractGenericFactory.determineAndCacheActualTypeTag(AbstractGenericFactory.java:56)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.AbstractGenericFactory.determineAndCacheActualTypeTag(AbstractGenericFactory.java:42)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.SimpleGenericFactory.createValues(SimpleGenericFactory.java:36)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:151)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:138)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveTuple(PrefabValues.java:79)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveOther(PrefabValues.java:102)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$changeField$2(FieldModifier.java:97)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$change$3(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.util.Rethrow.lambda$rethrow$0(Rethrow.java:47)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:30)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:45)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:55)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:100)
	at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:52)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:174)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:163)
	at nl.jqno.equalsverifier.internal.util.Configuration.ensureUnequalExamples(Configuration.java:198)
	at nl.jqno.equalsverifier.internal.util.Configuration.build(Configuration.java:98)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.buildConfig(SingleTypeEqualsVerifierApi.java:359)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:345)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:290)
// skipping stack trace elements outside of EqualsVerifier ...
```
I'm able to solve the problem by supplying prefabricated values of subtypes of `JsonNode` that implement `equals(Object)`:

```java
// showing only the added line for bevity:
.withPrefabValues(JsonNode.class, NullNode.instance, new TextNode("foo"))
```
***Example 2 (cannot be worked around :cloud_with_rain: )***

Invocation of EqualsVerifier:

```java
        EqualsVerifier.forClass(PactReenactment.class)
            .usingGetClass()
            // will NOT do the trick: .withPrefabValues(JsonNode.class, NullNode.instance, new TextNode("foo"))
            .withIgnoredFields("pactId")
            .suppress(STRICT_INHERITANCE)
            .verify();
```
Code in addition to the one from above:

```java
// ...
// i.e. other type parameter than Pact:
public class PactReenactment extends PactLike<InteractionReenactment> {
   // ...
```

```java
// ...
public class InteractionReenactment extends Interaction {
   // ...
```
Error message:

```
java.lang.AssertionError: EqualsVerifier found a problem in class de.monochromata.contract.reenactment.PactReenactment.
-> Missing implementation of resolved method 'abstract boolean equals(java.lang.Object)' of abstract class com.fasterxml.jackson.databind.JsonNode.

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:294)
	at de.monochromata.contract.reenactment.ReenactmentStepdefs.equalsVerifier(ReenactmentStepdefs.java:151)
	at ✽.de.monochromata.contract.reenactment.PactReenactment has prefabricated values and correct hashcode and equals methods(classpath:de/monochromata/contract/reenactment/Reenactment.feature:472)
Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract boolean equals(java.lang.Object)' of abstract class com.fasterxml.jackson.databind.JsonNode.
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveOther(PrefabValues.java:109)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$changeField$2(FieldModifier.java:97)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$change$3(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.util.Rethrow.lambda$rethrow$0(Rethrow.java:47)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:30)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:45)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:55)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:100)
	at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:52)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:174)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:163)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.giveInstances(FallbackFactory.java:95)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:40)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:155)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:138)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.traverseFields(FallbackFactory.java:88)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:39)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:155)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:138)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.AbstractGenericFactory.determineAndCacheActualTypeTag(AbstractGenericFactory.java:56)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.AbstractGenericFactory.determineAndCacheActualTypeTag(AbstractGenericFactory.java:42)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.SimpleGenericFactory.createValues(SimpleGenericFactory.java:36)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:151)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:138)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveTuple(PrefabValues.java:79)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveOther(PrefabValues.java:102)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$changeField$2(FieldModifier.java:97)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$change$3(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.util.Rethrow.lambda$rethrow$0(Rethrow.java:47)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:30)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:45)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:55)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:100)
	at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:52)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:174)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:163)
	at nl.jqno.equalsverifier.internal.util.Configuration.ensureUnequalExamples(Configuration.java:198)
	at nl.jqno.equalsverifier.internal.util.Configuration.build(Configuration.java:98)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.buildConfig(SingleTypeEqualsVerifierApi.java:359)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:345)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:290)
// skipping stack trace elements outside of EqualsVerifier ...
```

Adding prefabricated values does not solve the problem in this example:

```java
.withPrefabValues(JsonNode.class, NullNode.instance, new TextNode("foo"))
```

```
java.lang.AssertionError: EqualsVerifier found a problem in class de.monochromata.contract.reenactment.InteractionReenactment.
-> Receiver class com.fasterxml.jackson.databind.JsonNode$$DynamicSubclass$2067180044 does not define or inherit an implementation of the resolved method 'boolean equals(java.lang.Object)' of class java.lang.Object.

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:294)
	at de.monochromata.cucumber.stepdefs.EqualsVerifierStepdefs.correctAndAddsState(EqualsVerifierStepdefs.java:21)
	at ✽.de.monochromata.contract.reenactment.InteractionReenactment adds state to the super-class and has correct hashcode and equals methods(classpath:de/monochromata/contract/reenactment/Reenactment.feature:474)
Caused by: java.lang.AbstractMethodError: Receiver class com.fasterxml.jackson.databind.JsonNode$$DynamicSubclass$2067180044 does not define or inherit an implementation of the resolved method 'boolean equals(java.lang.Object)' of class java.lang.Object.
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveOther(PrefabValues.java:109)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$changeField$2(FieldModifier.java:97)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$change$3(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.util.Rethrow.lambda$rethrow$0(Rethrow.java:47)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:30)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:45)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:55)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:100)
	at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:52)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:174)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:163)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.giveInstances(FallbackFactory.java:95)
	at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:40)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:155)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:138)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveTuple(PrefabValues.java:79)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveOther(PrefabValues.java:102)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$changeField$2(FieldModifier.java:97)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$change$3(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.util.Rethrow.lambda$rethrow$0(Rethrow.java:47)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:30)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:45)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:55)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:100)
	at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:52)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:174)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:163)
	at nl.jqno.equalsverifier.internal.util.Configuration.ensureUnequalExamples(Configuration.java:198)
	at nl.jqno.equalsverifier.internal.util.Configuration.build(Configuration.java:98)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.buildConfig(SingleTypeEqualsVerifierApi.java:359)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:345)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:290)
// skipping stack trace elements outside of EqualsVerifier ...
```

**Expected behavior**
Would be great if prefabricated values would also work around the problem of example 2.

**Version**
3.5.4 - but problem also reproduced with 3.7.1

**Additional context**
Thanks for creating EqualsVerifier - it's a great tool :1st_place_medal:

**Comment by monochromata** [comment]
I hope you didn't read the ticket yet :slightly_smiling_face:  I had another assertion in the same test for example 2 that also needed the fix with the prefabricated values. Applied that and now the test is green. So all there is left to say is a big thank you for creating EqualsVerifier :sun_with_face: :bow:

**Comment by jqno** [comment]
Haha, I like it when issues close themselves like this ;). I do appreciate the effort you put into the original ticket btw, even if it turned out not to be needed after all. The more information, the better.
And thanks for the kind words!
