### ISSUE TITLE
NullPointerException testing JPA entities after weaving, _persistence_cacheKey (org.eclipse.persistence.internal.identitymaps.CacheKey)

### ISSUE THREAD

**Issue by markuspfeiffer** [jqno/equalsverifier#552]
Testing JPA entities fails after weaving. Weaving adds several transient "_persistence_X" fields, including `_persistence_cacheKey` of type `org.eclipse.persistence.internal.identitymaps.CacheKey`. The issue seems to be caused by `CacheKey`s equals implementation not accepting null values.

Unfortunately no combination of ignored fields or warnings seems to be able to fix this, since the exception happens in `buildConfig` before these take effect. The field itself is transient, so should actually be ignored by default?

Reproduced with both version 3.7.2 and 3.8.

I can't share the original code, due to it being a large proprietary Spring boot application, but the same issue can be reproduced with this piece of sample code:

```java
package com.example;

import java.util.Objects;

import org.junit.Test;

import nl.jqno.equalsverifier.EqualsVerifier;


public class EqualsVerifierVsCacheKey {

	/**
	 * Stand in for the actual entity after weaving
	 */
	private static class TheEntity {

		private final String field;

		/**
		 * Offending field added by weaving - actual type is org.eclipse.persistence.internal.identitymaps.CacheKey
		 */
		protected transient EqualsVerifierVsCacheKey.CacheKey _persistence_cacheKey;

		public TheEntity(final String field) {
			this.field = field;
		}

		@Override
		public boolean equals(final Object o) {
			if (this == o) {
				return true;
			}
			if (o == null || getClass() != o.getClass()) {
				return false;
			}
			final TheEntity theEntity = (TheEntity) o;
			return Objects.equals(field, theEntity.field);
		}

		@Override
		public int hashCode() {
			return Objects.hash(field);
		}
	}

	/**
	 * Simplified version of org.eclipse.persistence.internal.identitymaps.CacheKey
	 */
	private static class CacheKey {

		protected Object key;

		public CacheKey(final Object primaryKey) {
			this.key = primaryKey;
		}

		public boolean equals(final Object object) {
			try {
				return equals((CacheKey) object);
			} catch (final ClassCastException incorrectType) {
				return false;
			}
		}

		public boolean equals(final CacheKey key) {
			if (this == key) {
				return true;
			}
			return this.key.equals(key.key);
		}
	}

	@Test
	public void testEquals() {
		EqualsVerifier.forClass(TheEntity.class)
				.withIgnoredFields("_persistence_cacheKey")
				.usingGetClass()
				.verify();
	}
}
```

Running the test produces the following exception (taken from the actual test, to give correct line numbers for CacheKey):
```
java.lang.AssertionError: EqualsVerifier found a problem in class <redacted>.ActualEntity.
-> <no message>

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages

	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:308)
	at <redacted>.ActualEntity.testEquals(ActualEntityTest.java:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.NullPointerException
	at org.eclipse.persistence.internal.identitymaps.CacheKey.equals(CacheKey.java:329)
	at org.eclipse.persistence.internal.identitymaps.CacheKey.equals(CacheKey.java:315)
	at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveOther(PrefabValues.java:109)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$changeField$2(FieldModifier.java:97)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$change$3(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.util.Rethrow.lambda$rethrow$0(Rethrow.java:47)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:30)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:45)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:55)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:113)
	at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:100)
	at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:52)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:174)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:163)
	at nl.jqno.equalsverifier.internal.util.Configuration.ensureUnequalExamples(Configuration.java:198)
	at nl.jqno.equalsverifier.internal.util.Configuration.build(Configuration.java:98)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.buildConfig(SingleTypeEqualsVerifierApi.java:373)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:359)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:304)
	... 28 more
```

**Comment by jqno** [comment]
Thanks for submitting this. I can reproduce the issue, but I'm not sure yet what the best way is to resolve this. I'll let you know when I have a solution.

Unfortunately, even transient fields have to be instantiated, because if EqualsVerifier doesn't, it would get NullPointerExceptions occasionally. It's kind of ironic that you actually get one now *because* EqualsVerifier instantiates a transient field, instead of the other way round.

**Comment by markuspfeiffer** [comment]
Thanks for your reply. I was afraid it might not be a simple solution, but I was hoping I had missed something obvious while stepping through the code :sweat_smile: 

I spent some time with the debugger just now and was able to get a successful test run by manipulating the return value here:
```java
FieldIterable#createFieldList()
((ArrayList<Field>) result).removeIf(f -> f.name.startsWith("_persistence_"))
```

The particular class under test contains two additional entities (it's a many-to-many join table), so their `_persistence_` fields also needed to be removed. The breakpoint was set to stop for these entities.

If there was a way to make this behavior configurable it could possibly solve this?

Maybe something like
```java
excludeFieldForType(Entity.class, field -> field.name.startsWith("_persistence_"));
```

**Comment by jqno** [comment]
I managed to fix the issue by simply adding a null check :wink:
A new release (3.8.1) is now syncing with Maven Central, but it's been slow lately so it might take a while to appear.

**Comment by jqno** [comment]
So the important thing for you is, if you update to 3.8.1, you don't have to change anything else in your test, it should just work.

**Comment by markuspfeiffer** [comment]
Hi, thanks for the new version. I can confirm that version 3.8.1 does fix the NPE 😄

Unfortunately I keep running into more issues with other `_persistence_*` fields 😢 I've had to add several more prefab-values, but I'm now basically stuck in a state where I have to either provide a valid `org.eclipse.persistence.sessions.Session` or mock a large number of its methods. This feels very much overkill to test the equals method of a simple entity.

For now I'll simply `@Ignore` this test. Let me know if you think it worthwhile to create a repro with an actual entity/dependencies, rather than my simple mock object above.

**Comment by jqno** [comment]
I have to admit that I don't have a lot of experience using JPA, so I've not run into these issues myself before. Which library are you using for that? Hibernate, EclipseLink, something else?
Also, you mention that this happens "after weaving". Is it an option to run the EqualsVerifier test before weaving?

**Comment by markuspfeiffer** [comment]
Our product uses EclipseLink. I'm afraid I'm not very proficient with it myself. I know enough to use it, but I don't know all the ins and outs of our setup. But I'm sure I could get a co-worker to help, if needed (it being holiday season, probably not that quickly)

Unfortunately doing it before weaving isn't really an option, since the tests are run on our CI server. Changing the setup would potentially break other stuff, like integration tests. I can run the test fine locally, but having it run automatically would be preferable, of course.

**Comment by jqno** [comment]
Of course. Running the tests on a CI server is super important.
Maybe it would be good if you can talk to your coworkers to see if they can think of a simple fix. Otherwise, maybe if you can create a simple Maven (or Gradle) project that contains EclipseLink and EqualsVerifier and that reproduces the problem? That way I can try it out myself to see if I can come up with something from my end.
Although, due to the holiday season, it may be a while for me as well before I have time to look at it. So, no need to rush :).

I'll reopen this ticket for now.

**Comment by jqno** [comment]
Hi! Any updates on this?

**Comment by markuspfeiffer** [comment]
Sorry for the delay, I was a bit preoccupied with work :sweat_smile:

Here's a reproduction: https://github.com/markuspfeiffer/eclipselink-vs-equalsverifier. You should be able to reproduce the issue by running
```
./gradlew test --info
```

This currently complains about missing prefabs
> Add prefab values for one of the following types: FetchGroup, EntityFetchGroup

You can work around this by adding an additional prefab:
```
final var fetchGroupA = new EntityFetchGroup("fetch-group-a");
final var fetchGroupB = new EntityFetchGroup("fetch-group-b");

EqualsVerifier.forClass(StudentTeacher.class)
    …
    .withPrefabValues(FetchGroup.class, fetchGroupA, fetchGroupB)
```
This results in an error because of `'abstract boolean isUnitOfWork()' of interface org.eclipse.persistence.sessions.Session`. Mocking the Session class is… not easy :grimacing: 

You can get the test to complete fine if you disable weaving. To do this, comment out everything below
> EclipseLink static weaving Gradle task

in the `build.gradle` file

**Comment by jqno** [comment]
Thanks for the reproduction repo! It works (or rather, fails) exactly in the way you describe. I'll investigate if I can do something about it.

**Comment by jqno** [comment]
So I took another look, and I'm afraid I have to disappoint you... I've added the prefabs for FetchGroup, and this is the error message I get:


```
StudentTeacherTest > testEquals() FAILED
    java.lang.AssertionError: EqualsVerifier found a problem in class com.example.StudentTeacher.
    -> Abstract delegation: StudentTeacher's equals method delegates to an abstract method:
     Receiver class org.eclipse.persistence.sessions.Session$$DynamicSubclass$2120259176 does not define or inherit an implementation of the resolved method 'abstract boolean isUnitOfWork()' of interface org.eclipse.persistence.sessions.Session.

    For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
        at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:314)
        at com.example.StudentTeacherTest.testEquals(StudentTeacherTest.java:42)

        Caused by:
        nl.jqno.equalsverifier.internal.exceptions.AssertionException
            at nl.jqno.equalsverifier.internal.util.Assert.fail(Assert.java:76)
            at nl.jqno.equalsverifier.internal.checkers.AbstractDelegationChecker.checkAbstractMethods(AbstractDelegationChecker.java:121)
            at nl.jqno.equalsverifier.internal.checkers.AbstractDelegationChecker.checkAbstractDelegation(AbstractDelegationChecker.java:83)
            at nl.jqno.equalsverifier.internal.checkers.AbstractDelegationChecker.check(AbstractDelegationChecker.java:40)
            at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verifyWithoutExamples(SingleTypeEqualsVerifierApi.java:409)
            at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:376)
            at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:312)
            ... 1 more

            Caused by:
            java.lang.AbstractMethodError: Receiver class org.eclipse.persistence.sessions.Session$$DynamicSubclass$2120259176 does not define or inherit an implementation of the resolved method 'abstract boolean isUnitOfWork()' of interface org.eclipse.persistence.sessions.Session.
                at org.eclipse.persistence.queries.FetchGroup.onUnfetchedAttribute(FetchGroup.java:149)
                at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:98)
                at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3022)
                at com.example.StudentTeacher._persistence_checkFetched(StudentTeacher.java)
                at com.example.StudentTeacher._persistence_get_student(StudentTeacher.java)
                at com.example.StudentTeacher.equals(StudentTeacher.java:62)
                at nl.jqno.equalsverifier.internal.checkers.AbstractDelegationChecker.checkAbstractMethods(AbstractDelegationChecker.java:113)
                ... 6 more
```

So indeed, as you describe, the problem is now located in the `Session` class.

The stacktrace originates in the class's `equals` method, which (as you know) looks like this:

```
    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final StudentTeacher that = (StudentTeacher) o;
        return Objects.equals(student, that.student) && Objects.equals(teacher, that.teacher);
    }

```

The issue happens in the line that starts with the `return` statement. Apparently, the weaving replaces the reference to the property (`student`) with a generated method call (`_persistence_get_student()`) which in turn calls the `Session` object.

The way EqualsVerifier works, is by instantiating an object and using reflection to change the values of its fields. I guess the weaved code doesn't support that.

Since this all actually happens inside the `equals` method itself, there really isn't any way to get around this, except by providing a working `Session` object, or by disabling weaving somehow.

So unfortunately, I don't think this is something I can fix in EqualsVerifier.
