### ISSUE TITLE
record in JDK17 -  EqualsVerifier.forClass(XXX.class).verify() - fails

### ISSUE THREAD

**Issue by khmarbaise** [jqno/equalsverifier#637]
**Describe the bug**
I have tried to use equalsVerifier on a particular `record` in JDK17 which unfortunately failed.

**To Reproduce**
Create a JDK17 record like this:
```java
public record XRecord(int numerator, int denominator) {
  public XRecord(int numerator, int denominator) {
    if (denominator == 0) {
      throw new IllegalArgumentException("denominator is not allowed to be zero.");
    }

    this.numerator = numerator;
    this.denominator = denominator;
  }
}
```
and run a test on it like this:
```java
  @Test
  void name() {
    EqualsVerifier.forClass(XRecord.class).usingGetClass().verify();
  }
```
which fails with the described error message.

So in comparison I have created a usual class:
```java
public class Record {

  private final int numerator;

  private final int denominator;

  public Record(int numerator, int denominator) {
    if (denominator == 0) {
      throw new IllegalArgumentException("denominator is not allowed to be zero.");
    }
    this.numerator = numerator;
    this.denominator = denominator;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Record record = (Record) o;
    return numerator == record.numerator &&
        denominator == record.denominator;
  }

  @Override
  public int hashCode() {
    return Objects.hash(numerator, denominator);
  }

}
```
and running an equivalent test on it:
```java
  @Test
  void name() {
    EqualsVerifier.forClass(Record.class).usingGetClass().verify();
  }
```
which is successful.

**Code that triggers the behavior**
see above

**Error message**
```
Caused by: nl.jqno.equalsverifier.internal.exceptions.ReflectionException: Record: failed to invoke constructor.
  If the record does not accept 0 as a value for its fields, consider providing valid prefab values for those fields and suppressing Warning.ZERO_FIELDS.
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:34)
	at nl.jqno.equalsverifier.internal.reflection.RecordObjectAccessor.callRecordConstructor(RecordObjectAccessor.java:140)
	at nl.jqno.equalsverifier.internal.reflection.RecordObjectAccessor.makeAccessor(RecordObjectAccessor.java:119)
	at nl.jqno.equalsverifier.internal.reflection.RecordObjectAccessor.clear(RecordObjectAccessor.java:81)
	at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getDefaultValuesAccessor(ClassAccessor.java:239)
	at nl.jqno.equalsverifier.internal.checkers.RecordChecker.check(RecordChecker.java:36)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verifyWithoutExamples(SingleTypeEqualsVerifierApi.java:409)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:376)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:312)
     ... 70 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at nl.jqno.equalsverifier.internal.reflection.RecordObjectAccessor.lambda$callRecordConstructor$4(RecordObjectAccessor.java:141)
	at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:30)
	... 78 more
Caused by: java.lang.IllegalArgumentException: denominator is not allowed to be zero.
	at com.soebes.kata.fraction.XRecord.<init>(XRecord.java:7)
	... 85 more
```

**Version**
Version 3.10.

Added full reproducer project:

https://github.com/khmarbaise/issue-reproducer-equalsverifier-637

**Comment by jqno** [comment]
Thanks for the elaborate report! Makes it so much easier to debug these things :)

This is because for records, EqualsVerifier can't bypass the constructor when building instances, like it can do with regular classes. `0` happens to be one of the values it tries to initialize these instances with.

The problem can be avoided by adding `.suppress(Warning.ZERO_FIELDS)` to the EqualsVerifier call.

I've created a PR to your issue reproducer that shows the fix.

**Comment by khmarbaise** [comment]
First thanks for your reply. 

In records you can't bypass the constructor based on the implementation in JDK itself, but does that mean that using a usual class equalsverifier will bypass the constructor for filed injection, which this tests exactly is showing?

That's exactly the thing which puzzled me bit because of the different behaviour in contradiction to the usage of an exception in both cases. So from my understanding the behaviour should exactly the same... may be I miss a thing here...

Also which puzzles me is that the exception is given by the constructor which I expect to get in both cases?

**Comment by jqno** [comment]
Yes, for normal classes, EqualsVerifier bypasses the constructor completely. It uses Objenesis to create an instance without calling the constructor. (How Objenesis does that exactly, I don't know 😅. I do know it has different strategies, dependent on the JVM version and vendor. I think one of the possible strategies involves serialization.)

Then it uses reflection to fill in values for each of the fields. This way the code in the constructor, including the exception, is never run. This means that an object can have a state that violates its invariants, but for checking equals and hashcode, that usually doesn't really matter.

In hindsight, I'm not particularly proud of this approach. Something using generators, like in property based testing, would probably have been better. However, when I came up with it over 10 years ago, I didn't know about all that, and this has served well enough so far, so I never made the effort to change it 😄.

For records, this didn't work, so EqualsVerifier will check whether a class is a record or a regular class. If it's a regular class, it will use the approach above. If it's a record, it will call the constructor. This is possible because there's a one-to-one mapping between fields and constructor parameters (the compiler enforces this), which is something you can't rely on with regular classes, so I can't do that for regular classes, unfortunately.
