### ISSUE TITLE
 NullChecker false positive on non-nullable collection

### ISSUE THREAD

**Issue by jcamerin** [jqno/equalsverifier#745]
Within my project, we often choose to make collection fields null-safe by declaring them final and initializing them to empty collection.  The getter will return a copy and the setter will clear the collection and copy in any new elements. 

`import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class Simple {

    private final List<String> collection = new ArrayList<>();

    public List<String> getCollection() {
        return new ArrayList<>(collection);
    }

    public void setCollection(final List<String> collection) {
        this.collection.clear();
        if (collection != null) {
            this.collection.addAll(collection);
        }
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Simple)) {
            return false;
        }
        final Simple simple = (Simple) o;
        return getCollection().equals(simple.getCollection());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCollection());
    }
}`

As you can see in the class definition, the implementation prevents the field collection from being set to null. 

`import nl.jqno.equalsverifier.EqualsVerifier;
import org.junit.Test;

public class SimpleTest {

    @Test
    public void testEqualsHashCode() {
        EqualsVerifier.forClass(Simple.class).verify();
    }
}`

Given the test class and this latest version of equals verifier I am getting a failure from the null checker on these fields.  

java.lang.AssertionError: EqualsVerifier found a problem in class com.messagegears.accelerator.bo.Simple.
-> Non-nullity: equals throws NullPointerException on field collection.

For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
(EqualsVerifier 3.12.3, JDK 1.8.0_144 on Mac OS X)

	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:314)
	at com.messagegears.accelerator.bo.SimpleTest.testEqualsHashCode(SimpleTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
	at nl.jqno.equalsverifier.internal.util.Assert.fail(Assert.java:76)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.npeThrown(NullPointerExceptionFieldCheck.java:91)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.handle(NullPointerExceptionFieldCheck.java:75)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.performTests(NullPointerExceptionFieldCheck.java:58)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.execute(NullPointerExceptionFieldCheck.java:52)
	at nl.jqno.equalsverifier.internal.checkers.FieldInspector.check(FieldInspector.java:29)
	at nl.jqno.equalsverifier.internal.checkers.NullChecker.check(NullChecker.java:24)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verifyWithoutExamples(SingleTypeEqualsVerifierApi.java:417)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:384)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:312)
	... 28 more
Caused by: java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:177)
	at com.messagegears.accelerator.bo.Simple.getCollection(Simple.java:12)
	at com.messagegears.accelerator.bo.Simple.equals(Simple.java:31)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.lambda$performTests$0(NullPointerExceptionFieldCheck.java:58)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.NullPointerExceptionFieldCheck.handle(NullPointerExceptionFieldCheck.java:73)
	... 35 more

**Comment by jqno** [comment]
I understand your point, and this is a good design pattern to follow. Unfortunately there's no way for EqualsVerifier to see that you've already initialized your fields like this, so it still has to do the null checks.

You can work around this by calling `withNonnullFields` (if you want to be specific about the fields this applies to) or by suppressing the `NULL_FIELDS` warning (if you want it to apply for all fields)

**Comment by jcamerin** [comment]
Thank you!
