### ISSUE TITLE
Equals fails for lazy fields unused in equals method

### ISSUE THREAD

**Issue by mmcmm** [jqno/equalsverifier#752]
**Describe the bug**
I have an entity with an equals just on the id field and the verifier fails, saying I have no getter, but I don't use the lazy field in equals.

java.lang.AssertionError: EqualsVerifier found a problem in class ......
-> JPA Entity: direct reference to field tags used in equals instead of getter getTags.
```
For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
(EqualsVerifier 3.12.3, JDK 17.0.5 on Mac OS X)

	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:314)
	at .shouldVerifyEquals(EntitySerialIdCommonModelTest.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106

```

I did some debug and error is in this code, seems it expects to go in catch but it doesn`t

```
  if (!this.ignoredFields.contains(fieldName) && this.fieldIsLazy(fieldAccessor)) {
            this.assertEntity(fieldName, "equals", getterName, this.accessor.hasMethod(getterName, new Class[0]));
            ClassAccessor<T> subAccessor = this.throwingGetterAccessor(getterName);
            T red1 = subAccessor.getRedObject(TypeTag.NULL);
            T red2 = subAccessor.getRedObject(TypeTag.NULL);
            boolean equalsExceptionCaught = false;

            try {
                red1.equals(red2);
            } catch (EqualsVerifierInternalBugException var13) {
                equalsExceptionCaught = true;
            }
```

**Comment by jqno** [comment]
Hi!

I agree that the error message is a little confusing in this case, and I'll try to improve that in the next version.

But the behaviour is correct. As you can read [on the EqualsVerifier website](https://jqno.nl/equalsverifier/manual/jpa-entities/), by default, EqualsVerifier assumes a business or natural key for JPA entities, i.e. it assumes that all fields _except_ the id field participate in `equals`. It sounds like your class has a surrogate key, i.e. one where _only_ the id field participates in `equals`. In that case, you need to add `.suppress(Warning.SURROGATE_KEY)`. For more details, please check the website.
