### ISSUE TITLE
Equals Verfier assigns valus ignoring generic types

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jqno/equalsverifier#84]
```
What steps will reproduce the problem?
1. Using Equals Verifier test a class bearing List<non-String> property
2. Observe incomprehensible exception


What is the code (equals method, hashCode method, relevant fields) that
triggers the problem?

import java.util.List;

import nl.jqno.equalsverifier.EqualsVerifier;
import nl.jqno.equalsverifier.Warning;

public class EqVTest {

	public static class ClassA {

	}

	public static class ClassB {
		private List<ClassA> elements;

		public List<ClassA> getElements() {
			return elements;
		}

		public void setElements(List<ClassA> elements) {
			this.elements = elements;
		}

		@Override
		public int hashCode() {
			final int prime = 31;
			int result = 1;
			result = prime * result + ((elements == null) ? 0 : elements.hashCode());
			return result;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			ClassB other = (ClassB) obj;
			if (elements == null) {
				if (other.elements != null)
					return false;
			} else if (!elements.equals(other.elements))
				return false;
			return true;
		}

		@Override
		public String toString() {
			String tos = "ClassB(";
			for (ClassA e : elements) {
				tos += "" + e + ",";
			}
			tos += ")";
			return tos;
		}
	}

	public static void main(String[] args) {
		EqualsVerifier.forClass(ClassB.class) //
				.withRedefinedSuperclass() //
				.suppress(Warning.STRICT_INHERITANCE) //
				.suppress(Warning.NONFINAL_FIELDS) //
				.suppress(Warning.TRANSIENT_FIELDS) //
				.suppress(Warning.IDENTICAL_COPY_FOR_VERSIONED_ENTITY) //
				.verify();
	}
}


What error message does EqualsVerifier give?

Exception in thread "main" java.lang.AssertionError: Subclass: object is not 
equal to an instance of a trivial subclass with equal fields:
  [ClassB elements=[red]]-throws ClassCastException(java.lang.String cannot be cast to EqVTest$ClassA)
Consider making the class final.
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:347)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:330)
	at EqVTest.main(EqVTest.java:66)



What stacktrace does EqualsVerifier print, when called with the debug()
method?


What did you expect?
Passing test. Or a comprehensible exception at least. Not ClassCastException.

What version of EqualsVerifier are you using?
1.3.1

```

Original issue reported on code.google.com by `piotr.fi...@gmail.com` on 3 Sep 2013 at 7:11

**Comment by jqno** [comment]
This has been included in version 2.0!
